Feature/retailer/add product
sinhaugoh/DEALL pull request #29
Opened 2021-08-07 05:08 UTC by Kwang-Kian-Hui

2021-08-07 05:39 UTC, sinhaugoh requested changes

2021-08-07 05:39 UTC, sinhaugoh commented on lib/core/infrastructure/firestore_failures.dart
>  }
too much failure i think.

2021-08-07 05:39 UTC, sinhaugoh commented on lib/core/presentation/routes/app_router.dart
>      MaterialRoute(page: RetailerProfilePage),
duplicate add product page

2021-08-07 05:39 UTC, sinhaugoh commented on lib/core/shared/providers.dart
> +        (ref) => ProductListNotifier(ref.watch(productListRepoProvider)));
The product list shouldn't be in core, coz retailer use stream of product, but consumer use future

2021-08-07 05:39 UTC, sinhaugoh commented on lib/retailer/application/add_product_form_notifier.dart
> +        image: state.imageFile.toString(),
this shouldn't be working need to use uploadProductImage in imagePicking repo, refer to retailer sign up notifier.

2021-08-08 05:18 UTC, Kwang-Kian-Hui commented
Changes made, tested and works exactly as it should for products with and without image

2021-08-08 12:31 UTC, sinhaugoh requested changes
overall looks good, just minor change needed

2021-08-08 12:31 UTC, sinhaugoh commented on lib/core/infrastructure/product/product_dto.dart
> +  }
dont need to do tojson and fromJson manually, can just remove

2021-08-08 12:31 UTC, sinhaugoh commented on lib/core/application/value_validator.dart
> +}
for validation of usual price and discounted price u can check if it is empty first, if it is then return empty failure, then proceed to check with invalid value

2021-08-08 12:31 UTC, sinhaugoh commented on lib/retailer/application/add_product_form_notifier.dart
> +      final pid = _productRepository.getProductId(uid);
try to use productId instead. make the variable name meaningful

2021-08-08 12:31 UTC, sinhaugoh commented on lib/retailer/application/add_product_form_notifier.dart
> +
can just use newProduct.copyWith(image: filePath)

2021-08-08 12:31 UTC, sinhaugoh commented on lib/retailer/infrastructure/product_repository.dart
> +  String getProductId(String uid){
can rename to generateNewProductId? sounds more meaningful

2021-08-09 08:02 UTC, sinhaugoh requested changes

2021-08-09 08:02 UTC, sinhaugoh commented on lib/retailer/application/add_product_form_notifier.dart
> +    );
need to redo this part, logic error

2021-08-09 08:38 UTC, sinhaugoh approved these changes
everything correct

2021-08-09 11:37 UTC, merged